export const SET_LOADING = "SET_LOADING"
export const SET_ERROR = "SET_ERROR"
export const SET_MOVIES = "SET_MOVIES"
export const SET_SIMILAR_MOVIES = "SET_SIMILAR_MOVIES"
export const SET_DETAIL = "SET_DETAIL"
export const SET_LATEST = "SET_LATEST"
